### PR TITLE
Fix the `binary_partition` copy constructor.

### LINKED ISSUE #1683: Compilation error with intel compiler
With meep-1.19 Intel compiler stops with following:

--
CXX      sphere-quad.o
  CXXLD    sphere_quad
  CXX      array_slice.lo
In file included from meep.hpp(25),
                 from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep/vec.hpp(306): warning #3497: standard attribute syntax is a C++11 feature
  [[noreturn]] extern void abort(const char *, ...); // mympi.cpp
  ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(818): error: qualified name is not allowed
    std::unique_ptr<binary_partition> bp;
    ^

In file included from meep_internals.hpp(20),
                 from  #array_slice.cpp(27):
meep.hpp(818): error #77: this declaration has no storage class or type specifier
    std::unique_ptr<binary_partition> bp;
    ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(818): error: expected a ";"
    std::unique_ptr<binary_partition> bp;
                   ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(822): error: namespace "std" has no member "unique_ptr"
  std::unique_ptr<binary_partition> choose_chunkdivision(grid_volume &gv, volume &v, int num_chunks,
       ^
In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(822): error: expected a ";"
  std::unique_ptr<binary_partition> choose_chunkdivision(grid_volume &gv, volume &v, int num_chunks,
                 ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(1407): warning #3495: rvalue references are a C++11 feature
    void add_source(field_type ft, src_vol &&src);
                                           ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(2183): error: namespace "std" has no member "unique_ptr"
    binary_partition(const split_plane &_split_plane, std::unique_ptr<binary_partition> &&left_tree,
                                                           ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(2183): error: expected a ")"
    binary_partition(const split_plane &_split_plane, std::unique_ptr<binary_partition> &&left_tree,
                                                                     ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(2200): error: qualified name is not allowed
    std::unique_ptr<binary_partition> left;
    ^

In file included from meep_internals.hpp(20),
                 from array_slice.cpp(27):
meep.hpp(2200): error #77: this declaration has no storage class or type specifier
    std::unique_ptr<binary_partition> left;
    ^
--

This error was inintroduced after meep-1.18.
I tried versions intel-2017.2.174  and intel-2019.0.117 with -std=c++11 option.

### LINKED ISSUE #1701: Meep make fails to compile structure_dump.cpp
I am trying to build meep on master node of a cluster running Red Hat Linux.
I build parallel version with OpenMPI.
I was able to configure meep with `./configure` ([config.log](https://github.com/NanoComp/meep/files/6876257/config.log)), but `make` fails ([make.log](https://github.com/NanoComp/meep/files/6876242/make.log)) on compiling structure_dump.cpp with the error:
```
structure_dump.cpp:427:110: error: cannot convert ‘const meep::split_plane’ to ‘meep::direction’ in initialization
binary_partition::binary_partition(const binary_partition& other) : proc_id{other.proc_id}, plane{other.plane} {
                                                                                                             ^
```
I tried to build both with master branch and release 1.19 and faced the same error.
Possibly relevant environment data:
* `gcc-4.8.5`
* `hdf5-1.10.7`
* `openmpi-4.1.1`
* `libctl-4.5.0`

Any clue on what is going on?
Thanks

### PR DESCRIPTION
**Pull request by ahoenselaar**
Prevents issues with older compilers.
Closes #1683, closes #1701

### CODE REVIEW

File: src/structure_dump.cpp [hunk 1]
```diff
@@ -424,7 +424,7 @@ binary_partition::binary_partition(const split_plane &_split_plane,
   if (!left || !right) { meep::abort("Binary partition tree is required to be full"); }
 }
 
-binary_partition::binary_partition(const binary_partition& other) : proc_id{other.proc_id}, plane{other.plane} {
+binary_partition::binary_partition(const binary_partition& other) : proc_id{other.proc_id}, plane(other.plane) {
```
Comment (stevengj) [inline src/structure_dump.cpp:427]: Why are you using braces for `proc_id` and parens for `plane`?

Comment (stevengj) [reply src/structure_dump.cpp:427]: Interesting discussion here: https://probablydance.com/2013/02/02/the-problems-with-uniform-initialization/ … 

It's a stylistic question, but since we don't use "uniform initialization" elsewhere, and it is apparently exactly equivalent to old-style paren initialization, and it seems to occasionally cause problems with some compiler, maybe it is better to stick with parens

Comment (stevengj) [reply src/structure_dump.cpp:427]:
```suggestion
binary_partition::binary_partition(const binary_partition& other) : proc_id(other.proc_id), plane(other.plane) {
```

Comment (ahoenselaar) [reply src/structure_dump.cpp]: Ok

**Comment by ahoenselaar** [comment]
This should probably be backported into the 1.19 release.

**Comment by ahoenselaar** [comment]
Test failure looks unrelated to this change. Likely caused by #1698.

**Comment by oskooi** [comment]
The failing test in `test_special_kz.py` just checks that the runtime for some use case is less than that of another. It should *not* be affected by the choice of floating-point precision of the fields introduced in #1698. I simply restarted the CI and it is passing now. If we find that this particular test fails again in the future, we can disable it for single precision (the one that is failing) but we should keep it unmodified for now.
