### PR TITLE
Fix bug in `get_eigenmode` for `diffractedplanewave` object

### LINKED ISSUE #1950: incorrect results when using `DiffractedPlanewave` in `get_eigenmode_coefficient` to compute reflected diffraction orders of a binary grating
When trying to compute a single reflected diffraction order (m=+1) over a broad bandwidth of a binary-phase grating (adapted from [Tutorial/Diffraction Spectrum of a Binary Grating](https://meep.readthedocs.io/en/latest/Python_Tutorials/Mode_Decomposition/#diffraction-spectrum-of-a-binary-grating)) which involves passing a [`DiffractedPlanewave`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#diffractedplanewave) object as the `bands` parameter of [`get_eigenmode_coefficients`](https://meep.readthedocs.io/en/latest/Python_User_Interface/#mode-decomposition), one of the frequencies in the set unexpectedly produces an error:

(four numeric columns are: wavelength, angle of diffracted order, flux in *x* direction, diffraction efficiency)
```
refl:, 0.70000, 68.96, 0.02194235, 0.06366551
binary_grating_bug.py:117: RuntimeWarning: invalid value encountered in double_scalars
  mode_diff_eff.append(mode_refl[-1] / (Tair_glass * cosx))
refl:, 0.65116, 90.00, 0.00000000, nan
refl:, 0.60870, 71.81, 0.10426612, 0.34794817
refl:, 0.57143, 64.88, 0.06270599, 0.15386866
refl:, 0.53846, 63.63, 0.00553346, 0.01297542
refl:, 0.50909, 60.36, 0.11878936, 0.25017771
refl:, 0.48276, 59.56, 0.08148670, 0.16754566
refl:, 0.45902, 57.39, 0.06958019, 0.13448802
refl:, 0.43750, 56.85, 0.05490958, 0.10461123
refl:, 0.41791, 55.28, 0.03818814, 0.06983269
refl:, 0.40000, 54.90, 0.02459011, 0.04455002
```

Note the `nan` value for the mode at a wavelength of 0.65116 even though the modes at all other wavelengths are fine.

The output also shows that the failing mode is (incorrectly) an evanescent mode:

```
WARNING: diffraction order for g=(0,1,0) is evanescent!
```

Here are the relevant lines from `src/mpb.cpp` where this warning message is generated.

https://github.com/NanoComp/meep/blob/fa2467ac401100d20f33737216a00bbf2829a397/src/mpb.cpp#L602-L631

Printing out the relevant values for the evanescent mode which triggers this warning message reveals:
```
nn = 1.500000
frequency = 1.535714
k2sum = 5.481010
eig_vol=(0.000000,0.500000,0.000000)
kpoint=(1.216968,0.000000,0.000000)
```

The culprit here is `kpoint` which has a **non-zero** *x* component even though the simulation specified a `k_point` of zero. For some reason, MPB is *not* the computing the correct mode at this one particular frequency.

refl_grating_plot2D

```py
import meep as mp
import math
import numpy as np

resolution = 40        # pixels/μm                                                                                                                           

dpml = 1.0             # PML thickness                                                                                                                       
dsub = 4.0             # substrate thickness                                                                                                                 
dpad = 2.0             # padding between grating and PML                                                                                                     
gp = 0.5               # grating period                                                                                                                      
gh = 0.3               # grating height                                                                                                                      
gdc = 0.5              # grating duty cycle                                                                                                                  

sx = dpml+dsub+gh+dpad+dpml
sy = gp

cell_size = mp.Vector3(sx,sy,0)
pml_layers = [mp.PML(thickness=dpml,
                     direction=mp.X)]

wvl_min = 0.4           # min wavelength                                                                                                                     
wvl_max = 0.7           # max wavelength                                                                                                                     
fmin = 1/wvl_max        # min frequency                                                                                                                      
fmax = 1/wvl_min        # max frequency                                                                                                                      
fcen = 0.5*(fmin+fmax)  # center frequency                                                                                                                   
df = fmax-fmin          # frequency width                                                                                                                    

ng = 1.5
glass = mp.Medium(index=ng)

src_pt = mp.Vector3(-0.5*sx+dpml,0,0)
sources = [mp.Source(mp.GaussianSource(fcen, fwidth=df),
                     component=mp.Ez,
                     center=src_pt,
                     size=mp.Vector3(0,sy,0))]

k_point = mp.Vector3(0,0,0)

symmetries = [mp.Mirror(mp.Y)]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    k_point=k_point,
                    default_material=glass,
                    sources=sources,
                    symmetries=symmetries)

nfreq = 11
mon_pt = mp.Vector3(-0.5*sx+dpml+0.5*dsub,0,0)
flux_mon = sim.add_flux(fcen,
                        df,
                        nfreq,
                        mp.FluxRegion(center=mon_pt,
                                      size=mp.Vector3(0,sy,0)))

sim.run(until_after_sources=100)

input_flux = mp.get_fluxes(flux_mon)
input_flux_data = sim.get_flux_data(flux_mon)

sim.reset_meep()

geometry = [mp.Block(material=glass,
                     size=mp.Vector3(dpml+dsub,mp.inf,mp.inf),
                     center=mp.Vector3(-0.5*sx+0.5*(dpml+dsub),0,0)),
            mp.Block(material=glass,
                     size=mp.Vector3(gh,gdc*gp,mp.inf),
                     center=mp.Vector3(-0.5*sx+dpml+dsub+0.5*gh,0,0))]

sim = mp.Simulation(resolution=resolution,
                    cell_size=cell_size,
                    boundary_layers=pml_layers,
                    geometry=geometry,
                    k_point=k_point,
                    sources=sources,
                    symmetries=symmetries)

mode_mon = sim.add_flux(fcen,
                        df,
                        nfreq,
                        mp.FluxRegion(center=mon_pt,
                                      size=mp.Vector3(0,sy,0)))

sim.load_minus_flux_data(mode_mon, input_flux_data)

sim.plot2D(eps_parameters={'frequency':fmax})
plt.savefig('refl_grating_plot2D.png',bbox_inches='tight')

sim.run(until_after_sources=500)

freqs = mp.get_eigenmode_freqs(mode_mon)

res = sim.get_eigenmode_coefficients(mode_mon,
                                     mp.DiffractedPlanewave([0,+1,0],s=1,p=0),
                                     eig_parity=mp.ODD_Z+mp.EVEN_Y)
coeffs = res.alpha
kdom = res.kdom

mode_wvl = []
mode_angle = []
mode_refl = []
mode_diff_eff = []

for nf in range(nfreq):
  mode_wvl.append(1/freqs[nf])
  cosx = kdom[nf].x/(ng*freqs[nf])
  mode_angle.append(math.degrees(math.acos(cosx)))
  refl = abs(coeffs[0,nf,1])**2/input_flux[nf]
  mode_refl.append(0.5*refl)
  Tair_glass = 4*ng/(1+ng)**2
  mode_diff_eff.append(mode_refl[-1] / (Tair_glass * cosx))
  print("refl:, {:.5f}, {:.2f}, {:.8f}, {:.8f}".format(mode_wvl[-1],mode_angle[-1],mode_refl[-1],mode_diff_eff[-1]))
```

### PR DESCRIPTION
**Pull request by oskooi**
Fixes #1950.

### CODE REVIEW

File: src/mpb.cpp [hunk 1]
```diff
@@ -604,10 +604,10 @@ void *fields::get_eigenmode(double frequency, direction d, const volume where, c
     int m = 0;
     LOOP_OVER_DIRECTIONS(v.dim, dd) {
       m = dp->get_g()[dd - X];
```
Comment (stevengj) [inline src/mpb.cpp:606]: Might be worth putting this line inside the `if` as well.
