### PR TITLE
Fix bug for 3D simulation using 1D cell and single-precision floating point

### LINKED ISSUE #2916: Segmentation fault for 3D simulation using 1D cell
I am running into an unexpected segmentation fault when trying to run a 3D simulation using a 1D cell. This only occurs for certain grid resolutions and Bloch-periodic boundary conditions. 

This issue can be reproduced using the script below which involves a point source in vacuum with Bloch-periodic boundaries in $x$ and $y$ (`k_point = (-0.2, -0.2, 0)`). The simulation is fine when `RESOLUTION_UM` is `51` but produces the segfault for values of 52 and 53. Changing the `k_point` also runs fine (no segfault).

The problem therefore seems to be some combination of the grid resolution and the Bloch-periodic boundaries for a 1D cell. I should also mention that I am using Meep compiled using single-precision floating point and OpenMP.

**Case 1: `RESOLUTION_UM = 51`**
```
Initializing structure...
time for choose_chunkdivision = 7.7198e-05 s
Working in 3D dimensions.
Computational cell is 0.0196078 x 0.0196078 x 12 with resolution 51
time for set_epsilon = 0.00449374 s
-----------
Meep: using complex fields.
field decay(t = 50.009803921568626): 0.2511579661675122 / 0.2511579661675122 = 1.0
field decay(t = 100.01960784313725): 0.25115618711643334 / 0.2511579661675122 = 0.9999929166050117
field decay(t = 150.02941176470588): 1.7969355984235213e-10 / 0.2511579661675122 = 7.154603239719811e-10
run 0 finished at t = 150.02941176470588 (15303 timesteps)

Elapsed run time = 2.3554 s
```

**Case 2: `RESOLUTION_UM = 52`**
```
Using MPI version 3.1, 1 processes
-----------
Initializing structure...
time for choose_chunkdivision = 9.0651e-05 s
Working in 3D dimensions.
Computational cell is 0.0192308 x 0.0192308 x 12 with resolution 52
time for set_epsilon = 0.00381082 s
-----------
Meep: using complex fields.
[devbig095:2604209:0:2604209] Caught signal 11 (Segmentation fault: address not mapped to object at address (nil))
==== backtrace (tid:2604209) ====
 0  /lib64/libucs.so.0(ucs_handle_error+0x2e4) [0x7ff45fc81e44]
 1  /lib64/libucs.so.0(+0x2a4cd) [0x7ff45fc834cd]
 2  /lib64/libucs.so.0(+0x2a6aa) [0x7ff45fc836aa]
 3  /home/oskooi/install/meep/src/.libs/libmeep.so.33(_ZN4meep6fields15step_boundariesENS_10field_typeE+0x4b4) [0x7ff465a314c4]
=================================
[devbig095:2604209] *** Process received signal ***
[devbig095:2604209] Signal: Segmentation fault (11)
```

```py
import meep as mp
import numpy as np

RESOLUTION_UM = 51
WAVELENGTH_UM = 1.0

frequency = 1 / WAVELENGTH_UM
pml_um = 1.0
air_um = 10.0
size_z_um = pml_um + air_um + pml_um
cell_size = mp.Vector3(0, 0, size_z_um)

pml_layers = [mp.PML(thickness=pml_um)]

src_cmpt = mp.Ex

k_point = mp.Vector3(-0.2, -0.2, 0)

sources = [
    mp.Source(
        src=mp.GaussianSource(frequency, fwidth=0.1 * frequency),
        component=src_cmpt,
        center=mp.Vector3()
    )
]

sim = mp.Simulation(
    resolution=RESOLUTION_UM,
    force_complex_fields=True,
    cell_size=cell_size,
    sources=sources,
    boundary_layers=pml_layers,
    k_point=k_point
)

sim.run(
    until_after_sources=mp.stop_when_fields_decayed(
        50, src_cmpt, mp.Vector3(), 1e-6
    )
)
```

### PR DESCRIPTION
**Pull request by oskooi**
Fixes #2916.

**Root cause analysis**

The segfault occurs in `fields::step_boundaries()` (`src/step.cpp:263`) when dereferencing a pointer from the `outgoing_connection` vector at an out-of-bounds index.

The bug is in `connect_the_chunks()` (`src/boundaries.cpp`), which has **two passess** over not-owned boundary voxels:

1. **First pass** (line 480): Counts `comm_sizes` for each (`field_type`, `connect_phase`, `chunk_pair`) key. It determines `connect_phase` by comparing the Bloch phase as `complex<double>`: `const connect_phase ip = thephase == 1.0 ? CONNECT_COPY : ...`
2. **Second pass** (line 497): Sets up actual connection pointers. It determines `connect_phase` by comparing the Bloch phase as `complex<realnum>` (= `complx<float>` in single precision): `const connect_phase ip = thephase == static_cast<realnum>(1.0) ? CONNECT_COPY : ...`

When `eikna[X] == eikna[Y]` (because `kx == ky`), a boundary point requiring translation in both X and Y accumulates a combined phase of `conj(eikna[X]) * eikna[Y] = |eikna[X]|²`. In exact arithmetic this equals 1.0, but `cos²(θ) + sin²(θ)` computed in double-precision floating point has a tiny rounding error (~10⁻¹⁶). This error is:
- **Detectable in double precision**: `thephase != 1.0` → classified as `CONNECT_PHASE`
- **Below float precision** (~10⁻⁷): `float(thephase) == 1.0f` → classified as `CONNECT_COPY`

This mismatch means the first pass allocates space for 12 `CONNECT_PHASE` realnums, but the second pass only pushes 8 connection pointers (the other 4 go to `CONNECT_COPY` instead). When `step_boundaries` tries to read all 12, it accesses index 8 of an 8-element vector → segfault.

**Why resolution=51 works**: Different resolution produces different grid dimensions and chunk splits. The angle `θ = k * 2π/a * n` differs, so `cos²(θ) + sin²(θ)` may happen to equal exactly 1.0 in double (or the chunks may not have corner boundary points requiring both X and Y translations).

**Fix**

Change the second pass (line 497-500) to use `thephase_double` (the original `complex<double>` value) instead of `thephase` (the truncated `complex<float>` value) for the connect_phase classification. This ensures both passes use identical comparison.

**Test**

Added `test_1d_cell_bloch()` to `tests/three_d.cpp` that creates a D3 grid with nx=1, ny=1 (1D cell in 3D), resolution=52, `k_point=(-0.2, -0.2, 0)`, PML, and runs for several timesteps. Without the fix, this segfaults on the first step in single precision.

### CODE REVIEW

**Comment by stevengj** [comment]
Seems like we should check `if (eikna[X] == eikna[Y]) thephase = 1.0;` and hence use `CONNECT_COPY`, rather than relying on roundoff of `conj(eikna[X]) * eikna[Y]`

File: src/boundaries.cpp [hunk 1]
```diff
@@ -346,6 +346,21 @@ bool fields_chunk::needs_W_notowned(component c) {
...
 }
 
+/* approximate comparisons of phases to 1 or -1.   exp(ix) * exp(-ix) is not exactly 1
+   due to roundoff errors, but we want to treat it equal for the purpose of determining
+   the boundary conditions, because we have optimized b.c.'s for phase +1 and -1, and
+   roundoff errors on the order of 1e-13 are not significant relative to the truncation
+   errors in meep anyway.  (the alternative would be to accumulate symmetry phases more
+   accurately by adding exponents rather than multiplying). */
+static bool phase_isclose(std::complex<double> thephase, double realphase) {
+  return fabs(thephase.imag()) < 1e-13 && fabs(thephase.imag() - realphase) < 1e-13;
```
Comment (stevengj) [inline src/boundaries.cpp]:
```suggestion
  return fabs(thephase.imag()) < 1e-13 && fabs(thephase.real() - realphase) < 1e-13;
```
