### PR TITLE
Singleton DFT fix

### LINKED ISSUE #1269: Segmentation fault when calling 1-dim. DFT object
My Meep simulations break after timestepping and Eigenmode calculations due to a segmentation fault. 

It seems like this is related to the 1-dimensional DFT monitors I'm using in addition to the 2d flux monitor. As you can see from the output below, timestepping and MPB Eigenmode calculations work, but then something happens when `sim.get_dft_array()` is called and a segmentation fault stops the script:

```
[...long output from MPB...]
MPB solved for frequency_2(0,033,0,0) = 0,0294435 after 20 iters
MPB solved for frequency_2(0,046328,0,0) = 0,0410659 after 16 iters
MPB solved for frequency_2(0,046464,0,0) = 0,041183 after 10 iters
MPB solved for frequency_2(0,046464,0,0) = 0,041183 after 1 iters
Dominant planewave for band 2: (0,046464,-0,000000,0,000000)
MPB solved for frequency_2(0,033,0,0) = 0,0294435 after 20 iters
MPB solved for frequency_2(0,0465176,0,0) = 0,0412292 after 16 iters
MPB solved for frequency_2(0,0466579,0,0) = 0,04135 after 10 iters
MPB solved for frequency_2(0,0466579,0,0) = 0,04135 after 1 iters
Dominant planewave for band 2: (0,046658,-0,000000,0,000000)

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

I'm posting the script below. Essentially, what I'm trying to do is simulate the characteristic impedance of a microstrip transmission line. [https://www.3ds.com/products-services/simulia/resources/microstrip-transmission-line/](https://www.3ds.com/products-services/simulia/resources/microstrip-transmission-line/)

Most often, this equation is used: `Z_line = P / (I * conj(I))`

Hence, I'm using the flux from a 2d monitor as the power `P` and I'm trying to get the conducted current `I` from an H-field integration along a closed loop around the conductor (Ampère's law). For that loop, I place four 1d DFT monitors as line segements around the conductor:
loop_YZ_alpha0deg

Whatever I'm doing wrong here, it should probably not cause a seg fault. I have also tried using the DFT fields of the 2d flux monitor for the H field integration (integrating along its edges). That does not break the script, but the values are wrong, maybe because of incorrect weights for the 1d integration?

Here is the script. It works as is with the last section disabled by the comments. If you uncomment those lines, the SIGSEGV occurs.

```
import meep as mp
import numpy as np
import matplotlib.pyplot as mplt
import scipy.constants

# layout unit is 1mm
w = 2.9
h = 1.55
alpha = np.deg2rad(0)     # rotation angle of conductor
res = 4
f_cen = 0.033   # f_center = 10 GHz
df = 0.0167     # delta_f = 5 GHz

# create geometry
geometry = [mp.Block(size=mp.Vector3(mp.inf, mp.inf, h),
                     center=mp.Vector3(),
                     material=mp.Medium(epsilon=4.5)),
            mp.Block(size=mp.Vector3(mp.inf, mp.inf, 1/res),
                     center=mp.Vector3(z=-0.5 * h),
                     material=mp.perfect_electric_conductor),
            mp.Prism(vertices=[mp.Vector3(100 * np.cos(alpha) - 0.5 * w * np.sin(alpha),
                                          100 * np.sin(alpha) + 0.5 * w * np.cos(alpha),
                                          0.5 * (h - 1 / res)),
                               mp.Vector3(100 * np.cos(alpha) + 0.5 * w * np.sin(alpha),
                                          100 * np.sin(alpha) - 0.5 * w * np.cos(alpha),
                                          0.5 * (h - 1 / res)),
                               mp.Vector3(-100 * np.cos(alpha) + 0.5 * w * np.sin(alpha),
                                          -100 * np.sin(alpha) - 0.5 * w * np.cos(alpha),
                                          0.5 * (h - 1 / res)),
                               mp.Vector3(-100 * np.cos(alpha) - 0.5 * w * np.sin(alpha),
                                          -100 * np.sin(alpha) + 0.5 * w * np.cos(alpha),
                                          0.5 * (h - 1 / res))
                               ],
                     height=1 / res,
                     material=mp.perfect_electric_conductor)]

band = 2
parity = mp.NO_PARITY

# create source in XZ or YZ
if np.abs(np.cos(alpha)) > np.abs(np.sin(alpha)):
    source_size = mp.Vector3(0, 9, h)
else:
    source_size = mp.Vector3(9, 0, h)

sources = [mp.EigenModeSource(src=mp.GaussianSource(frequency=f_cen, fwidth=df),
                              center=mp.Vector3(-4 * np.cos(alpha), -4 * np.sin(alpha), 0),
                              size=source_size,
                              eig_band=band,
                              eig_parity=parity,
                              direction=mp.NO_DIRECTION,
                              eig_kpoint=mp.Vector3(f_cen * np.cos(alpha),
                                                    f_cen * np.sin(alpha),
                                                    0))]

sim = mp.Simulation(geometry=geometry,
                    resolution=res,
                    cell_size=mp.Vector3(30, 30, 30),
                    boundary_layers=[mp.PML(5)],
                    sources=sources)

sim.init_sim()

# add flux monitor
monitor_zmax = 4 * h
monitor_zmin = -0.5 * h
flux_monitor = sim.add_mode_monitor(f_cen, df, 101,
                                    mp.FluxRegion(center=mp.Vector3(4 * np.cos(alpha),
                                                                    4 * np.sin(alpha),
                                                                    0.5 * (monitor_zmax + monitor_zmin)),
                                                  size=mp.Vector3(source_size.x,
                                                                  source_size.y,
                                                                  monitor_zmax - monitor_zmin)))

# add DFT monitors for H fields
dft_Hz_pos = None
dft_Hz_neg = None
dft_Hx_pos = None
dft_Hx_neg = None
dft_Hy_pos = None
dft_Hy_neg = None
# add 4 line sections for H field integration around conductor
if np.abs(np.cos(alpha)) > np.abs(np.sin(alpha)):
    # create loop in YZ
    dft_Hy_neg = sim.add_dft_fields([mp.Hy], f_cen, df, 101,
                                center=mp.Vector3(5 * np.cos(alpha), 5 * np.sin(alpha), h),
                                size=mp.Vector3(source_size.x, source_size.y, 0))
    dft_Hy_pos = sim.add_dft_fields([mp.Hy], f_cen, df, 101,
                                center=mp.Vector3(5 * np.cos(alpha), 5 * np.sin(alpha), 0),
                                size=mp.Vector3(source_size.x, source_size.y, 0))
    dft_Hz_pos = sim.add_dft_fields([mp.Hz], f_cen, df, 101,
                                    center=mp.Vector3(5 * np.cos(alpha) - 0.5 * source_size.x * np.sin(alpha),
                                                      5 * np.sin(alpha) + 0.5 * source_size.y * np.cos(alpha),
                                                      0.5 * h),
                                    size=mp.Vector3(0, 0, h))
    dft_Hz_neg = sim.add_dft_fields([mp.Hz], f_cen, df, 101,
                                    center=mp.Vector3(5 * np.cos(alpha) + 0.5 * source_size.x * np.sin(alpha),
                                                      5 * np.sin(alpha) - 0.5 * source_size.y * np.cos(alpha),
                                                      0.5 * h),
                                    size=mp.Vector3(0, 0, h))
else:
    # create loop in XZ
    dft_Hx_pos = sim.add_dft_fields([mp.Hx], f_cen, df, 101,
                                    center=mp.Vector3(5 * np.cos(alpha), 5 * np.sin(alpha), h),
                                    size=mp.Vector3(source_size.x, source_size.y, 0))
    dft_Hx_neg = sim.add_dft_fields([mp.Hx], f_cen, df, 101,
                                    center=mp.Vector3(5 * np.cos(alpha), 5 * np.sin(alpha), 0),
                                    size=mp.Vector3(source_size.x, source_size.y, 0))
    dft_Hz_pos = sim.add_dft_fields([mp.Hz], f_cen, df, 101,
                                    center=mp.Vector3(5 * np.cos(alpha) - 0.5 * source_size.x * np.sin(alpha),
                                                      5 * np.sin(alpha) + 0.5 * source_size.y * np.cos(alpha),
                                                      0.5 * h),
                                    size=mp.Vector3(0, 0, h))
    dft_Hz_neg = sim.add_dft_fields([mp.Hz], f_cen, df, 101,
                                    center=mp.Vector3(5 * np.cos(alpha) + 0.5 * source_size.x * np.sin(alpha),
                                                      5 * np.sin(alpha) - 0.5 * source_size.y * np.cos(alpha),
                                                      0.5 * h),
                                    size=mp.Vector3(0, 0, h))

# plot cross section for current loop in YZ
sim.plot2D(output_plane=mp.Volume(center=mp.Vector3(x=5), size=mp.Vector3(0, 30, 30)))
mplt.show()

sim.run(until_after_sources=mp.stop_when_fields_decayed(2 / f_cen, mp.Ez, mp.Vector3(4 * np.cos(alpha), 4 * np.sin(alpha), 0), 1e-3))

(coeffs, vgrp, kpoints, kdom, cscale) = sim.get_eigenmode_coefficients(
            flux=flux_monitor,
            bands=[band],
            eig_parity=parity,
            direction=mp.NO_DIRECTION,
            kpoint_func=lambda f, n: mp.Vector3(f_cen * np.cos(alpha), f_cen * np.sin(alpha), 0))

wave_fwd = coeffs[0, :, 0]
wave_bwd = coeffs[0, :, 1]
freqs_meep = np.array(mp.get_flux_freqs(flux_monitor))

# # integrate H fields along loop around conductor
# H_integral = np.zeros(len(freqs_meep), dtype=np.complex)
# for i_freq in range(len(freqs_meep)):
#
#     if dft_Hz_pos is not None:
#         Hz_pos = sim.get_dft_array(dft_Hz_pos, mp.Hz, i_freq)
#         (x, y, z, w) = sim.get_array_metadata(dft_cell=dft_Hz_pos)
#         H_integral[i_freq] += np.sum(w * Hz_pos)
#
#     if dft_Hz_neg is not None:
#         Hz_neg = sim.get_dft_array(dft_Hz_neg, mp.Hz, i_freq)
#         (x, y, z, w) = sim.get_array_metadata(dft_cell=dft_Hz_neg)
#         H_integral[i_freq] += np.sum(-1 * w * Hz_neg)
#
#     if dft_Hy_pos is not None:
#         Hy_pos = sim.get_dft_array(dft_Hy_pos, mp.Hy, i_freq)
#         (x, y, z, w) = sim.get_array_metadata(dft_cell=dft_Hy_pos)
#         H_integral[i_freq] += np.sum(w * Hy_pos)
#
#     if dft_Hy_neg is not None:
#         Hy_neg = sim.get_dft_array(dft_Hy_neg, mp.Hy, i_freq)
#         (x, y, z, w) = sim.get_array_metadata(dft_cell=dft_Hy_neg)
#         H_integral[i_freq] += np.sum(-1 * w * Hy_neg)
#
#     if dft_Hx_pos is not None:
#         Hx_pos = sim.get_dft_array(dft_Hx_pos, mp.Hx, i_freq)
#         (x, y, z, w) = sim.get_array_metadata(dft_cell=dft_Hx_pos)
#         H_integral[i_freq] += np.sum(w * Hx_pos)
#
#     if dft_Hx_neg is not None:
#         Hx_neg = sim.get_dft_array(dft_Hx_neg, mp.Hx, i_freq)
#         (x, y, z, w) = sim.get_array_metadata(dft_cell=dft_Hx_neg)
#         H_integral[i_freq] += np.sum(-1 * w * Hx_neg)
#
# # calculate microstrip impedance
# Z0 = np.sqrt(scipy.constants.mu_0 / scipy.constants.epsilon_0)
# zline = mp.get_fluxes(flux_monitor) / np.real(H_integral * np.conjugate(H_integral)) * Z0
```

### PR DESCRIPTION
**Pull request by smartalecH**
Fixes #1269 

There were actually two bugs here. First, a collapsed array size counter (`reduced_dims`) was uninitialized. If the array to be collapsed only consisted of a single element, it wouldn't update to the correct value. Consequently, the routine would try to create an array the size of whatever garbage was in memory (which would occasionally cause a segfault).

Next, the actual singleton DFT calculation was never copied to the garbage array (assuming no segfault occurred).

Note there are still probably some other bugs in the `collapse_array()` routine (`array_slice.cpp`). If we see more odd behavior with DFT fields (e.g. when symmetries are applied, weird field components, etc.) we should first look here. Then we should look in `_get_dft_array()` inside of `meep.i`.

### CODE REVIEW

**Comment by smartalecH** [comment]
As discussed I check for singleton cases earlier and return.

However, I noticed there is another bug that still requires the initialization of `reduced_dims`.

Taking the simple example in #1269, if the user specifies a line with size (1,22,1) (i.e. two dimensions need to be collapsed), then the reduced stride is set to garbage:

https://github.com/NanoComp/meep/blob/5ad4b8407084a839133e92a7638bb6d94b140b38/src/array_slice.cpp#L678-L680

The comment in the code seems to assume that the reduced stride _would_ be set to zero by default.

**Comment by stevengj** [comment]
The later code should be:
```cxx
if (reduced_rank == 2) {
    if (reduced_stride[0] != 0)
      reduced_stride[0] = reduced_dims[1];
    else if (reduced_stride[1] != 0)
      reduced_stride[1] = reduced_dims[1];
}
```
Basically, it should never access elements of `reduced_dims` ≥`reduced_rank `

**Comment by smartalecH** [comment]
Fixed -- should be ready for merging after tests pass.

File: src/array_slice.cpp [hunk 1]
```diff
@@ -662,6 +662,10 @@ double *collapse_array(double *array, int *rank, size_t dims[3], direction dirs[
       reduced_dims[reduced_rank++] = dims[r];
     }
   }
+  if (reduced_rank==0) {
+    *rank = 0;
+    return array; // return array as is for singleton use case
+  }
```
Comment (stevengj) [inline src/array_slice.cpp:668]: It looks like this change should not have been here, see #3010 — a single output point is still interpolated from multiple DFT points. 

Maybe at the point this PR was made, we didn't have true interpolation for DFT fields, and if you asked for a single-point DFT it just snapped it to the nearest grid point?  But in that case you would have `reduced_rank == full_rank == 0`, so this change should still have been unnecessary?
